version: '3'
services:
    web:
        build: .
        tty: true
        ports:
            - "5000:5000"
        env_file:
            - ./.env
        volumes:
            - .:/home/hsm
        depends_on:
            - postgres
        networks:
            - db_nw
            - web_nw
    postgres:
        image: "postgres:9.6.5"
        environment:
            - POSTGRES_USER=hsm
            - POSTGRES_PASSWORD=hsm
            - POSTGRES_DB=hsm-db
            - POSTGRES_PORT=5432
        networks:
            - db_nw
        restart: always 
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
