version: '3'
services:
    web:
        build: .
        tty: true
        container_name: ${CONTAINER_NAME_WEB}
        restart: always
        ports:
            - "${HOST_PORT}:8080"
        environment:
            - DB_NAME=${DB_NAME}
            - DB_ADDR=${DB_ADDR}
        env_file:
            - ./.env
        volumes:
            - .:/home/hsm
        depends_on:
            - db
        networks:
            - db_nw
            - web_nw
        entrypoint:
            - ./docker-entrypoint.sh
    db:
        image: "postgres:9.6.5"
        container_name: ${CONTAINER_NAME_DB}
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PORT=5432
        networks:
            - db_nw
        restart: always 
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
