version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
        environment:
          TZ: America/New_York
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgres://postgres@localhost/hsm-db
          CI_TESTING: true

      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_USER: hsm
          POSTGRES_DB: hsm-db
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install --dev

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Put sample environment variables in place
          command: |
            cp sample.env .env

      - run:
          name: HSM test suite
          command: |
            cd HSM
            pipenv run python -m unittest

      - run:
          name: Flake8
          command: |
            pipenv run flake8
