version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
        environment:
          TZ: America/New_York
          PIPENV_VENV_IN_PROJECT: true
          CI_TESTING: "TRUE"

      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_USER: hsm
          POSTGRES_DB: hsm-db
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "HSM/requirements-dev.txt" }}-{{ checksum "HSM/requirements.txt"}}

      - run:
          name: Setup environment
          command: |
            python -m venv venv
            . venv/bin/activate

            pip install -r HSM/requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "HSM/requirements-dev.txt" }}-{{ checksum "HSM/requirements.txt"}}

      - run:
          name: HSM test suite
          command: |
            . venv/bin/activate
            cd HSM
            python -m unittest tests/test_db.py

      - run:
          name: Flake8
          command: |
            . venv/bin/activate
            flake8